name: Epimanager CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate Project Structure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check Essential Files
        run: |
          if [ ! -f package.json ]; then
            echo "::error::Arquivo package.json não encontrado!"
            exit 1
          fi
          echo "Estrutura do projeto validada com sucesso!"

  install:
    name: Install Dependencies
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install Packages
        run: npm ci

  build:
    name: Build Project
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - run: npm ci
      - run: npm run build
